server:
  port: 18080

spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/ebook?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:generator/*.xml
  type-aliases-package: com.tianzhen.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


yuedu:
  loginUrl: 'https://cloud.yuedu.pro/auth/customer/password/token'
  searchUrl: 'https://cloud.yuedu.pro/netdisk/search/file/page'
  username: 504618712@qq.com
  password: 504618712@qq.com
  grant_type: 'customer_password'
  defaultBear: 'Basic cGlnOnBpZw=='
  USER_AGENT: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36'
  Referer: 'https://cloud.yuedu.pro/'
  Accept-Language: 'zh-CN,zh;q=0.9'
  Accept: '*/*'